#pragma checksum "TabExample.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "E480101109EFFE5C64B30D29AED453816BE9E511D29C1D20694B9B7C6538B47D"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Fusion.UI;
using Ngdbeambracketconnect;
using Ngdbeambracketconnect.Converter;
using Ngdbeambracketconnect.Model;
using Ngdbeambracketconnect.ViewModel;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Tekla.Structures.Dialog.UIControls;


namespace Ngdbeambracketconnect {
    
    
    /// <summary>
    /// TabExample
    /// </summary>
    public partial class TabExample : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 83 "TabExample.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel HotRolled;
        
        #line default
        #line hidden
        
        
        #line 98 "TabExample.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox HotRolledProfile;
        
        #line default
        #line hidden
        
        
        #line 105 "TabExample.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel BuiltUp;
        
        #line default
        #line hidden
        
        
        #line 136 "TabExample.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox BUWebThickness;
        
        #line default
        #line hidden
        
        
        #line 145 "TabExample.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel Stiffner;
        
        #line default
        #line hidden
        
        
        #line 180 "TabExample.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cblCountry;
        
        #line default
        #line hidden
        
        
        #line 188 "TabExample.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cblBracket;
        
        #line default
        #line hidden
        
        
        #line 247 "TabExample.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox BracketEPThickness;
        
        #line default
        #line hidden
        
        
        #line 250 "TabExample.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox BracketEPWidth;
        
        #line default
        #line hidden
        
        
        #line 254 "TabExample.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox BeamEPThickness;
        
        #line default
        #line hidden
        
        
        #line 257 "TabExample.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox BeamEPWidth;
        
        #line default
        #line hidden
        
        
        #line 336 "TabExample.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox BoltGage;
        
        #line default
        #line hidden
        
        
        #line 340 "TabExample.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox OuterBoltOffset;
        
        #line default
        #line hidden
        
        
        #line 344 "TabExample.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox OuterBoltQuantity;
        
        #line default
        #line hidden
        
        
        #line 352 "TabExample.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox OutsideOverhang;
        
        #line default
        #line hidden
        
        
        #line 360 "TabExample.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InnerBoltQuantity;
        
        #line default
        #line hidden
        
        
        #line 364 "TabExample.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InnerBoltOffset;
        
        #line default
        #line hidden
        
        
        #line 368 "TabExample.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox InsideOverhang;
        
        #line default
        #line hidden
        
        
        #line 405 "TabExample.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel HotRolled1;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Ngdbeambracketconnect;component/tabexample.xaml", System.UriKind.Relative);
            
            #line 1 "TabExample.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.HotRolled = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 2:
            this.HotRolledProfile = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            this.BuiltUp = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 4:
            this.BUWebThickness = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.Stiffner = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 6:
            this.cblCountry = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 7:
            this.cblBracket = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 8:
            this.BracketEPThickness = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.BracketEPWidth = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.BeamEPThickness = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.BeamEPWidth = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            this.BoltGage = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            this.OuterBoltOffset = ((System.Windows.Controls.TextBox)(target));
            return;
            case 14:
            this.OuterBoltQuantity = ((System.Windows.Controls.TextBox)(target));
            return;
            case 15:
            this.OutsideOverhang = ((System.Windows.Controls.TextBox)(target));
            return;
            case 16:
            this.InnerBoltQuantity = ((System.Windows.Controls.TextBox)(target));
            return;
            case 17:
            this.InnerBoltOffset = ((System.Windows.Controls.TextBox)(target));
            return;
            case 18:
            this.InsideOverhang = ((System.Windows.Controls.TextBox)(target));
            return;
            case 19:
            this.HotRolled1 = ((System.Windows.Controls.StackPanel)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

